<?php
declare(strict_types=1);
namespace Meydan\Core\Integrations\Bale;
final class AdminPage {
 private const PAGE='meydan-bale-sync';
 public static function register():void{add_action('admin_menu',[self::class,'menu'],31);add_action('admin_post_meydan_bale_send_code',[self::class,'sendCode']);add_action('admin_post_meydan_bale_verify_code',[self::class,'verifyCode']);add_action('admin_post_meydan_bale_logout',[self::class,'logout']);}
 public static function menu():void{add_submenu_page('meydan','ورود بله','ورود بله','manage_options',self::PAGE,[self::class,'render']);}
 public static function render():void{if(!current_user_can('manage_options'))wp_die('دسترسی کافی ندارید.');$s=(new BaleServiceClient())->status();$ok=!is_wp_error($s)&&!empty($s['authorized']);echo '<div class="wrap"><h1>ورود حساب بله</h1><p>شماره و کد ورود ارسال می‌شود و Session فقط در سرویس بله رمزگذاری و ذخیره می‌شود.</p><div class="notice '.($ok?'notice-success':'notice-warning').'"><p>'.($ok?'حساب بله فعال است.':'حساب بله احراز هویت نشده است.').'</p></div>';if(is_wp_error($s))echo '<div class="notice notice-error"><p>'.esc_html($s->get_error_message()).'</p></div>';echo '<div style="max-width:760px;display:grid;gap:20px"><div class="card"><h2>۱. ارسال کد</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('meydan_bale_send_code');echo '<input type="hidden" name="action" value="meydan_bale_send_code"><p><label>شماره موبایل<br><input class="regular-text" name="phone" inputmode="tel" placeholder="0912... یا +98912..." required></label></p>';submit_button('ارسال کد بله','primary','submit',false);echo '</form></div><div class="card"><h2>۲. تأیید کد</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('meydan_bale_verify_code');echo '<input type="hidden" name="action" value="meydan_bale_verify_code"><p><label>شناسه چالش<br><input class="regular-text" name="challenge_id" required></label></p><p><label>کد ورود<br><input class="regular-text" name="code" inputmode="numeric" autocomplete="one-time-code" required></label></p>';submit_button('تأیید و ذخیره Session','primary','submit',false);echo '</form></div>';if($ok){echo '<div class="card"><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('meydan_bale_logout');echo '<input type="hidden" name="action" value="meydan_bale_logout">';submit_button('خروج از بله','delete','submit',false);echo '</form></div>';}echo '</div></div>';}
 public static function sendCode():void{self::guard('meydan_bale_send_code');$r=(new BaleServiceClient())->sendCode(sanitize_text_field((string)wp_unslash($_POST['phone']??'')));if(!is_wp_error($r)&&!empty($r['challenge_id']))set_transient('meydan_bale_challenge_'.get_current_user_id(),(string)$r['challenge_id'],600);self::finish($r,'کد ورود بله ارسال شد.');}
 public static function verifyCode():void{self::guard('meydan_bale_verify_code');$id=sanitize_text_field((string)wp_unslash($_POST['challenge_id']??''));if($id==='')$id=(string)get_transient('meydan_bale_challenge_'.get_current_user_id());$r=(new BaleServiceClient())->verifyCode($id,sanitize_text_field((string)wp_unslash($_POST['code']??'')));if(!is_wp_error($r))delete_transient('meydan_bale_challenge_'.get_current_user_id());self::finish($r,'حساب بله با موفقیت احراز هویت شد.');}
 public static function logout():void{self::guard('meydan_bale_logout');self::finish((new BaleServiceClient())->logout(),'Session بله حذف شد.');}
 private static function guard(string $a):void{if(!current_user_can('manage_options'))wp_die('دسترسی کافی ندارید.');check_admin_referer($a);}
 private static function finish(array|\WP_Error $r,string $success):never{set_transient('meydan_bale_notice_'.get_current_user_id(),['type'=>is_wp_error($r)?'error':'success','message'=>is_wp_error($r)?$r->get_error_message():$success],60);wp_safe_redirect(admin_url('admin.php?page='.self::PAGE));exit;}
}
