<?php

declare(strict_types=1);
namespace Meydan\Core\Rest;

use Meydan\Core\Audit\AuditLogger;
use Meydan\Core\Support\Cursor;
use Meydan\Core\Support\EventLogger;
use Meydan\Core\Support\Response;
use Meydan\Core\Support\Serializer;
use Meydan\Core\Support\Stats;
use WP_Query;
use WP_REST_Request;

final class ContentController extends BaseController
{
    public function list(WP_REST_Request $r){$offset=$this->offset((string)$r->get_param('cursor'));$args=['post_type'=>'meydan_content','post_status'=>'publish','posts_per_page'=>20,'offset'=>$offset,'orderby'=>'date','order'=>'DESC'];$mq=[];$tq=[];if($v=$r->get_param('format'))$mq[]=['key'=>'meydan_format','value'=>sanitize_key((string)$v)];if($this->bool($r->get_param('featured')))$mq[]=['key'=>'meydan_featured','value'=>'1'];if($v=$r->get_param('category'))$tq[]=['taxonomy'=>'meydan_content_category','field'=>is_numeric($v)?'term_id':'slug','terms'=>$v];if($v=$r->get_param('tag'))$tq[]=['taxonomy'=>'meydan_content_tag','field'=>'slug','terms'=>sanitize_title((string)$v)];if($mq)$args['meta_query']=$mq;if($tq)$args['tax_query']=$tq;$q=new WP_Query($args);$posts=$q->posts;if($cid=(int)$r->get_param('creator_id')){global $wpdb;$allowed=array_map('intval',$wpdb->get_col($wpdb->prepare("SELECT content_id FROM {$wpdb->prefix}meydan_content_creators WHERE creator_id=%d",$cid)));$posts=array_values(array_filter($posts,static fn($p)=>in_array((int)$p->ID,$allowed,true)));}$data=array_values(array_filter(array_map(fn($p)=>$this->enrich(Serializer::content($p),(int)$p->ID),$posts)));$next=count($q->posts)===20?Cursor::encode(['o'=>$offset+20]):null;return Response::cache(Response::ok($data,['next_cursor'=>$next]),'public, max-age=60, stale-while-revalidate=300');}
    public function get(WP_REST_Request $r){$id=(int)$r['id'];$data=Serializer::content($id);if(!$data)return Response::error('not_found','محتوا پیدا نشد.',404);Stats::incrementContent($id,'views',1);EventLogger::log('detail_open','content',$id);$data['stats']=Stats::content($id);return Response::cache(Response::ok($this->enrich($data,$id)),'public, max-age=60, stale-while-revalidate=300');}
    public function bookmark(WP_REST_Request $r){return $this->toggle((int)$r['id'],'bookmark',true);}
    public function unbookmark(WP_REST_Request $r){return $this->toggle((int)$r['id'],'bookmark',false);}
    public function share(WP_REST_Request $r){$id=(int)$r['id'];if(!Serializer::content($id))return Response::error('not_found','محتوا پیدا نشد.',404);Stats::incrementContent($id,'shares',1);EventLogger::log('share','content',$id);return Response::ok(['shared'=>true,'shares'=>Stats::content($id)['shares']]);}
    public function download(WP_REST_Request $r){$id=(int)$r['id'];$fid=(int)$r['file_id'];$c=Serializer::content($id);if(!$c)return Response::error('not_found','محتوا پیدا نشد.',404);$found=null;foreach($c['attachments'] as $a)if((int)$a['id']===$fid){$found=$a;break;}if(!$found)return Response::error('not_found','فایل پیدا نشد.',404);Stats::incrementContent($id,'downloads',1);EventLogger::log('download','content',$id,['file_id'=>$fid]);return Response::ok(['file'=>$found,'downloads'=>Stats::content($id)['downloads']]);}
    public function adminCreate(WP_REST_Request $r){if(!current_user_can('manage_meydan_content'))return Response::error('forbidden','دسترسی کافی ندارید.',403);return $this->save($r,0);}
    public function adminUpdate(WP_REST_Request $r){if(!current_user_can('manage_meydan_content'))return Response::error('forbidden','دسترسی کافی ندارید.',403);return $this->save($r,(int)$r['id']);}
    public function adminDelete(WP_REST_Request $r){if(!current_user_can('manage_meydan_content'))return Response::error('forbidden','دسترسی کافی ندارید.',403);$id=(int)$r['id'];$before=Serializer::content($id);if(!$before)return Response::error('not_found','محتوا پیدا نشد.',404);wp_trash_post($id);AuditLogger::log('content_deleted','content',$id,$before,['status'=>'trash']);return Response::ok(['deleted'=>true]);}
    private function save(WP_REST_Request $r,int $id){$p=$this->json($r);$before=$id?Serializer::content($id):null;if($id&&get_post_type($id)!=='meydan_content')return Response::error('not_found','محتوا پیدا نشد.',404);$post=['post_type'=>'meydan_content','post_status'=>sanitize_key((string)($p['status']??'publish')),'post_title'=>sanitize_text_field((string)($p['title']??($id?get_the_title($id):''))),'post_content'=>wp_kses_post((string)($p['body']??($id?get_post_field('post_content',$id):''))),'post_excerpt'=>sanitize_textarea_field((string)($p['excerpt']??($id?get_post_field('post_excerpt',$id):'')))];if($id){$post['ID']=$id;$res=wp_update_post($post,true);}else{$res=wp_insert_post($post,true);$id=is_wp_error($res)?0:(int)$res;}if(is_wp_error($res))return $this->error($res);foreach(['format','usage_note','subtitle','badge','location_label','media_duration'] as $k)if(array_key_exists($k,$p))update_post_meta($id,'meydan_'.$k,$k==='format'?sanitize_key((string)$p[$k]):sanitize_text_field((string)$p[$k]));if(array_key_exists('featured',$p))update_post_meta($id,'meydan_featured',(int)$this->bool($p['featured']));if(isset($p['attachments']))update_post_meta($id,'meydan_attachments',$this->attachments((array)$p['attachments']));if(isset($p['files']))update_post_meta($id,'meydan_files',(array)$p['files']);if(isset($p['tags']))wp_set_post_terms($id,array_map('sanitize_text_field',(array)$p['tags']),'meydan_content_tag');if(isset($p['category']))wp_set_post_terms($id,[(int)$p['category']],'meydan_content_category');if(isset($p['creators']))$this->syncCreators($id,(array)$p['creators']);AuditLogger::log($before?'content_updated':'content_created','content',$id,$before,Serializer::content($id));return Response::ok($this->enrich(Serializer::content($id),$id),[],$before?200:201);}
    private function enrich(?array $data,int $id):?array{if(!$data)return null;$post=get_post($id);$data['slug']=$post?$post->post_name:(string)$id;$data['subtitle']=(string)get_post_meta($id,'meydan_subtitle',true);$data['badge']=(string)get_post_meta($id,'meydan_badge',true);$data['location_label']=(string)get_post_meta($id,'meydan_location_label',true);$data['media_duration']=(string)get_post_meta($id,'meydan_media_duration',true);$data['files']=array_values((array)get_post_meta($id,'meydan_files',true));return $data;}
    private function toggle(int $id,string $action,bool $on){if(!is_user_logged_in())return Response::error('unauthenticated','برای این عملیات باید وارد شوید.',401);if(!Serializer::content($id))return Response::error('not_found','محتوا پیدا نشد.',404);global $wpdb;$uid=get_current_user_id();$table=$wpdb->prefix.'meydan_interactions';$exists=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$table} WHERE user_id=%d AND object_type='content' AND object_id=%d AND action=%s",$uid,$id,$action));if($on&&!$exists){$wpdb->insert($table,['user_id'=>$uid,'object_type'=>'content','object_id'=>$id,'action'=>$action,'created_at'=>current_time('mysql',true)]);Stats::incrementContent($id,'bookmarks',1);}elseif(!$on&&$exists){$wpdb->delete($table,['id'=>$exists]);Stats::incrementContent($id,'bookmarks',-1);}return Response::ok(['bookmarked'=>$on,'stats'=>Stats::content($id)]);}
    private function syncCreators(int $id,array $creators):void{global $wpdb;$table=$wpdb->prefix.'meydan_content_creators';$wpdb->delete($table,['content_id'=>$id]);foreach($creators as $i=>$c){$cid=is_array($c)?(int)($c['id']??$c['creator_id']??0):(int)$c;if($cid<=0||get_post_type($cid)!=='meydan_creator')continue;$wpdb->insert($table,['content_id'=>$id,'creator_id'=>$cid,'position'=>(int)(is_array($c)?($c['position']??$i):$i),'role_label'=>is_array($c)?sanitize_text_field((string)($c['role_label']??'')):null]);}}
    private function attachments(array $items):array{$out=[];foreach($items as $i=>$a){if(!is_array($a))continue;$mid=(int)($a['media_id']??$a['id']??0);if($mid<=0||get_post_type($mid)!=='attachment')continue;$out[]=['media_id'=>$mid,'order'=>(int)($a['order']??$i+1),'caption'=>isset($a['caption'])?sanitize_text_field((string)$a['caption']):null,'label'=>isset($a['label'])?sanitize_text_field((string)$a['label']):null];}return $out;}
    private function offset(string $c):int{$v=Cursor::decode($c);return max(0,(int)($v['o']??0));}
}
