<?php
declare(strict_types=1);namespace Meydan\Core\Rest;
use Meydan\Core\Support\EventLogger;use Meydan\Core\Support\Response;use Meydan\Core\Support\Serializer;use WP_Query;use WP_REST_Request;
final class InitiativeController extends BaseController
{
 public function list(){ $q=new WP_Query(['post_type'=>'meydan_initiative','post_status'=>'publish','posts_per_page'=>100,'orderby'=>'date','order'=>'DESC']);return Response::ok(array_values(array_filter(array_map([Serializer::class,'initiative'],$q->posts))));}
 public function get(WP_REST_Request $r){$d=Serializer::initiative((int)$r['id']);return $d?Response::ok($d):Response::error('not_found','ابتکار پیدا نشد.',404);}
 public function join(WP_REST_Request $r){return $this->toggle((int)$r['id'],true);}
 public function leave(WP_REST_Request $r){return $this->toggle((int)$r['id'],false);}
 private function toggle(int $id,bool $on){$initiative=Serializer::initiative($id);if(!$initiative)return Response::error('not_found','ابتکار پیدا نشد.',404);$v=$this->viewer();if(!$v->isAuthenticated()&&!$initiative['allow_guest_join'])return Response::error('unauthenticated','این ابتکار نیاز به ورود دارد.',401);global $wpdb;$table=$wpdb->prefix.'meydan_initiative_members';if($v->isAuthenticated()){$where=['initiative_id'=>$id,'user_id'=>$v->userId];$existing=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$table} WHERE initiative_id=%d AND user_id=%d",$id,$v->userId));$data=['initiative_id'=>$id,'member_type'=>'user','user_id'=>$v->userId,'guest_id'=>null];}else{$existing=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$table} WHERE initiative_id=%d AND guest_id=%s",$id,$v->id));$data=['initiative_id'=>$id,'member_type'=>'guest','user_id'=>null,'guest_id'=>$v->id];}if($on){if($existing)$wpdb->update($table,['status'=>'active','joined_at'=>current_time('mysql',true)],['id'=>$existing]);else{$data+=['joined_at'=>current_time('mysql',true),'status'=>'active'];$wpdb->insert($table,$data);}EventLogger::log('initiative_join','initiative',$id);}elseif($existing)$wpdb->update($table,['status'=>'left'],['id'=>$existing]);return Response::ok(['joined'=>$on,'participant_count'=>Serializer::initiative($id)['participant_count']]);}
}
