<?php
declare(strict_types=1);namespace Meydan\Core\Rest;
use Meydan\Core\Support\Response;use Meydan\Core\Support\Serializer;use WP_Query;use WP_REST_Request;
final class MiscController extends BaseController
{
 public function provinces(){global $wpdb;$rows=$wpdb->get_results("SELECT id,name,slug,sort_order FROM {$wpdb->prefix}meydan_provinces WHERE active=1 ORDER BY sort_order,name",ARRAY_A);return Response::cache(Response::ok(array_map(static fn($r)=>['id'=>(int)$r['id'],'name'=>$r['name'],'slug'=>$r['slug']],$rows?:[])),'public, max-age=300');}
 public function cities(WP_REST_Request $r){global $wpdb;$pid=(int)$r->get_param('province_id');$sql="SELECT id,province_id,name,slug,sort_order FROM {$wpdb->prefix}meydan_cities WHERE active=1";$args=[];if($pid){$sql.=' AND province_id=%d';$args[]=$pid;}$sql.=' ORDER BY sort_order,name';if($args)$sql=$wpdb->prepare($sql,...$args);$rows=$wpdb->get_results($sql,ARRAY_A);return Response::cache(Response::ok(array_map(static fn($x)=>['id'=>(int)$x['id'],'province_id'=>(int)$x['province_id'],'name'=>$x['name'],'slug'=>$x['slug']],$rows?:[])),'public, max-age=300');}
 public function reverse(WP_REST_Request $r){$lat=(float)$r->get_param('latitude');$lng=(float)$r->get_param('longitude');if($lat<-90||$lat>90||$lng<-180||$lng>180)return Response::error('validation_failed','مختصات موقعیت معتبر نیست.',422);$key='meydan_reverse_'.md5(number_format($lat,4,'.','').'|'.number_format($lng,4,'.',''));$data=get_transient($key);if($data===false){$url=add_query_arg(['format'=>'jsonv2','lat'=>$lat,'lon'=>$lng,'zoom'=>18,'addressdetails'=>1,'accept-language'=>'fa'], 'https://nominatim.openstreetmap.org/reverse');$res=wp_remote_get($url,['timeout'=>8,'headers'=>['User-Agent'=>'Meydan/1.0 (location picker)']]);if(is_wp_error($res))return Response::error('geocoding_unavailable','امکان تشخیص مکان وجود ندارد؛ دوباره تلاش کنید.',503);$json=json_decode((string)wp_remote_retrieve_body($res),true);if(!is_array($json)||empty($json['address']))return Response::error('geocoding_unavailable','مکان انتخاب‌شده شناسایی نشد.',422);$address=(array)$json['address'];$provinceName=(string)($address['state']??$address['province']??$address['region']??'');$cityName=(string)($address['city']??$address['town']??$address['village']??$address['municipality']??$address['county']??'');global $wpdb;$provinces=$wpdb->get_results("SELECT id,name FROM {$wpdb->prefix}meydan_provinces WHERE active=1",ARRAY_A)?:[];$provinceId=$this->placeId($provinces,$provinceName);$cities=$provinceId?$wpdb->get_results($wpdb->prepare("SELECT id,name FROM {$wpdb->prefix}meydan_cities WHERE active=1 AND province_id=%d",$provinceId),ARRAY_A)?:[]:[];$cityId=$this->placeId($cities,$cityName);$parts=array_filter([(string)($address['road']??''),(string)($address['neighbourhood']??$address['suburb']??''),$cityName,$provinceName]);$data=['latitude'=>$lat,'longitude'=>$lng,'address'=>mb_substr(implode('، ',array_unique($parts))?:((string)($json['display_name']??'')),0,255),'province_id'=>$provinceId?:null,'city_id'=>$cityId?:null,'province_name'=>$provinceName?:null,'city_name'=>$cityName?:null];set_transient($key,$data,HOUR_IN_SECONDS);}return Response::ok($data);}
 private function placeId(array $rows,string $name):int{$needle=$this->normalizePlace($name);if($needle==='')return 0;foreach($rows as $row){$candidate=$this->normalizePlace((string)$row['name']);if($candidate===$needle||str_contains($needle,$candidate)||str_contains($candidate,$needle))return (int)$row['id'];}return 0;}
 private function normalizePlace(string $value):string{$value=str_replace(['ي','ى','ك'],['ی','ی','ک'],$value);return preg_replace('/[^\p{L}\p{N}]/u','',mb_strtolower($value))?:'';}
 public function currentCampaign(){ $q=new WP_Query(['post_type'=>'meydan_campaign','post_status'=>'publish','posts_per_page'=>1,'meta_key'=>'meydan_current','meta_value'=>'1','orderby'=>'meta_value_num','order'=>'DESC']);$d=$q->posts?Serializer::campaign($q->posts[0]):null;return $d?Response::ok($d):Response::ok(null);}
 public function campaign(WP_REST_Request $r){$d=Serializer::campaign((int)$r['id']);return $d?Response::ok($d):Response::error('not_found','کمپین پیدا نشد.',404);}
 public function campaignSchedule(WP_REST_Request $r){$d=Serializer::campaign((int)$r['id']);return $d?Response::ok($d['schedule']??[]):Response::error('not_found','کمپین پیدا نشد.',404);}
 public function config(){return Response::cache(Response::ok(['feature_flags'=>(array)get_option('meydan_feature_flags',[]),'quick_actions'=>(array)get_option('meydan_quick_actions',[])]),'public, max-age=60, stale-while-revalidate=300');}
}
