<?php
declare(strict_types=1);namespace Meydan\Core\Rest;
use Meydan\Core\Notifications\NotificationService;use Meydan\Core\Support\Cursor;use Meydan\Core\Support\Response;use Meydan\Core\Support\Serializer;use WP_REST_Request;
final class NotificationController extends BaseController
{
 public function list(WP_REST_Request $r){if(!is_user_logged_in())return Response::error('unauthenticated','مرکز اعلان‌ها نیاز به ورود دارد.',401);$uid=get_current_user_id();$offset=$this->offset((string)$r->get_param('cursor'));$filter=sanitize_key((string)($r->get_param('filter')?:'all'));global $wpdb;$where='recipient_user_id=%d AND archived_at IS NULL';if($filter==='unread')$where.=' AND read_at IS NULL';$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM {$wpdb->prefix}meydan_notifications WHERE {$where} ORDER BY created_at DESC,id DESC LIMIT 20 OFFSET %d",$uid,$offset),ARRAY_A);$next=count($rows?:[])===20?Cursor::encode(['o'=>$offset+20]):null;return Response::cache(Response::ok(array_map([Serializer::class,'notification'],$rows?:[]),['next_cursor'=>$next]),'private, no-store');}
 public function unread(){if(!is_user_logged_in())return Response::error('unauthenticated','مرکز اعلان‌ها نیاز به ورود دارد.',401);global $wpdb;$n=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}meydan_notifications WHERE recipient_user_id=%d AND read_at IS NULL AND archived_at IS NULL",get_current_user_id()));return Response::cache(Response::ok(['count'=>$n]),'private, no-store');}
 public function read(WP_REST_Request $r){return $this->mark((int)$r['id'],'read_at',true);}
 public function unreadOne(WP_REST_Request $r){return $this->mark((int)$r['id'],'read_at',false);}
 public function readAll(){if(!is_user_logged_in())return Response::error('unauthenticated','مرکز اعلان‌ها نیاز به ورود دارد.',401);global $wpdb;$wpdb->query($wpdb->prepare("UPDATE {$wpdb->prefix}meydan_notifications SET read_at=UTC_TIMESTAMP() WHERE recipient_user_id=%d AND read_at IS NULL",get_current_user_id()));return Response::ok(['read_all'=>true]);}
 public function archive(WP_REST_Request $r){return $this->mark((int)$r['id'],'archived_at',true);}
 public function unarchive(WP_REST_Request $r){return $this->mark((int)$r['id'],'archived_at',false);}
 public function delete(WP_REST_Request $r){if(!is_user_logged_in())return Response::error('unauthenticated','مرکز اعلان‌ها نیاز به ورود دارد.',401);global $wpdb;$id=(int)$r['id'];$n=$wpdb->delete($wpdb->prefix.'meydan_notifications',['id'=>$id,'recipient_user_id'=>get_current_user_id()]);return $n?Response::ok(['deleted'=>true]):Response::error('not_found','اعلان پیدا نشد.',404);}
 public function broadcast(WP_REST_Request $r){if(!current_user_can('manage_meydan_notifications'))return Response::error('forbidden','دسترسی کافی ندارید.',403);$p=$this->json($r);if(empty($p['title'])||empty($p['body']))return Response::error('validation_failed','عنوان و متن اعلان الزامی است.',422);$n=(new NotificationService())->broadcast(sanitize_text_field((string)$p['title']),sanitize_textarea_field((string)$p['body']),(array)($p['audience']??['type'=>'all']),isset($p['deep_link'])?sanitize_text_field((string)$p['deep_link']):null);\Meydan\Core\Audit\AuditLogger::log('notification_broadcast','notification',null,null,['count'=>$n,'audience'=>$p['audience']??['type'=>'all']]);return Response::ok(['created'=>$n],[],201);}
 private function mark(int $id,string $field,bool $on){if(!is_user_logged_in())return Response::error('unauthenticated','مرکز اعلان‌ها نیاز به ورود دارد.',401);global $wpdb;$table=$wpdb->prefix.'meydan_notifications';$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE id=%d AND recipient_user_id=%d",$id,get_current_user_id()),ARRAY_A);if(!$row)return Response::error('not_found','اعلان پیدا نشد.',404);$wpdb->update($table,[$field=>$on?current_time('mysql',true):null],['id'=>$id]);$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE id=%d",$id),ARRAY_A);return Response::ok(Serializer::notification($row));}
 private function offset(string $c):int{$v=Cursor::decode($c);return max(0,(int)($v['o']??0));}
}
