<?php

declare(strict_types=1);
namespace Meydan\Core\Rest;
use Meydan\Core\Support\Response;use Meydan\Core\Support\Serializer;use WP_Query;use WP_REST_Request;
final class SquareController extends BaseController
{
 public function list(WP_REST_Request $r){$args=['post_type'=>'meydan_square','post_status'=>'publish','posts_per_page'=>100,'orderby'=>'title','order'=>'ASC'];if($q=trim((string)$r->get_param('q')))$args['s']=$q;$wpq=new WP_Query($args);$data=array_values(array_filter(array_map([Serializer::class,'square'],$wpq->posts)));if($r->has_param('verified')){$v=$this->bool($r->get_param('verified'));$data=array_values(array_filter($data,static fn($x)=>$x['verified']===$v));}foreach(['province_id','city_id'] as $k)if($id=(int)$r->get_param($k))$data=array_values(array_filter($data,static fn($x)=>($x['location'][$k]??0)===$id));return Response::cache(Response::ok($data),'public, max-age=60, stale-while-revalidate=300');}
 public function get(WP_REST_Request $r){$d=Serializer::square((int)$r['id']);return $d&&get_post_status((int)$r['id'])==='publish'?Response::cache(Response::ok($d),'public, max-age=60, stale-while-revalidate=300'):Response::error('not_found','میدان پیدا نشد.',404);}
 public function narratives(WP_REST_Request $r){$sid=(int)$r['id'];if(get_post_type($sid)!=='meydan_square')return Response::error('not_found','میدان پیدا نشد.',404);$q=new WP_Query(['post_type'=>'meydan_narrative','post_status'=>'publish','posts_per_page'=>50,'meta_query'=>[['key'=>'meydan_author_actor_type','value'=>'square'],['key'=>'meydan_author_actor_id','value'=>$sid]],'orderby'=>'date','order'=>'DESC']);return Response::ok(array_values(array_filter(array_map([Serializer::class,'narrative'],$q->posts))));}
 public function schedule(WP_REST_Request $r){$sid=(int)$r['id'];if(get_post_type($sid)!=='meydan_square')return Response::error('not_found','میدان پیدا نشد.',404);return Response::ok(Serializer::squareSchedule($sid));}
 public function map(WP_REST_Request $r){global $wpdb;$where=['p.post_type=\'meydan_square\'','p.post_status=\'publish\''];$args=[];foreach(['province_id','city_id'] as $k)if($r->get_param($k)!==null){$where[]='g.'.$k.'=%d';$args[]=(int)$r->get_param($k);}if($r->get_param('west')!==null){$where[]='g.longitude >= %f';$args[]=(float)$r->get_param('west');}if($r->get_param('east')!==null){$where[]='g.longitude <= %f';$args[]=(float)$r->get_param('east');}if($r->get_param('south')!==null){$where[]='g.latitude >= %f';$args[]=(float)$r->get_param('south');}if($r->get_param('north')!==null){$where[]='g.latitude <= %f';$args[]=(float)$r->get_param('north');}$sql="SELECT g.*,p.post_title FROM {$wpdb->prefix}meydan_square_geo g JOIN {$wpdb->posts} p ON p.ID=g.square_id WHERE ".implode(' AND ',$where)." LIMIT 1000";if($args)$sql=$wpdb->prepare($sql,...$args);$rows=$wpdb->get_results($sql,ARRAY_A);$features=[];foreach($rows?:[] as $row){$features[]=['type'=>'Feature','geometry'=>['type'=>'Point','coordinates'=>[(float)$row['longitude'],(float)$row['latitude']]],'properties'=>['id'=>(int)$row['square_id'],'name'=>$row['post_title'],'verified'=>(bool)get_post_meta((int)$row['square_id'],'meydan_verified',true),'city_id'=>(int)$row['city_id'],'avatar_url'=>\Meydan\Core\Support\Actor::mediaUrl((int)get_post_meta((int)$row['square_id'],'meydan_avatar_media_id',true))]];}return Response::cache(Response::ok(['type'=>'FeatureCollection','features'=>$features]),'public, max-age=60, stale-while-revalidate=300');}
}
