<?php

declare(strict_types=1);namespace Meydan\Core\Rest;
use Meydan\Core\Support\Actor;use Meydan\Core\Support\Handles;use Meydan\Core\Domain\UserAccess;use Meydan\Core\Support\Response;use Meydan\Core\Support\Serializer;use Meydan\Core\Support\SquareActivity;use WP_Query;use WP_REST_Request;
final class SquareController extends BaseController
{
 public function list(WP_REST_Request $r){$args=['post_type'=>'meydan_square','post_status'=>'publish','posts_per_page'=>min(100,max(1,(int)($r->get_param('limit')?:100))),'orderby'=>'title','order'=>'ASC'];if($q=trim((string)$r->get_param('q')))$args['s']=$q;if($r->has_param('verified')&&$this->bool($r->get_param('verified')))$args['meta_query']=[['key'=>'meydan_verified','value'=>'1']];$wpq=new WP_Query($args);$data=array_values(array_filter(array_map(fn($p)=>$this->enrich(Serializer::square($p),(int)$p->ID),$wpq->posts)));if($r->has_param('verified')){$v=$this->bool($r->get_param('verified'));$data=array_values(array_filter($data,static fn($x)=>$x['verified']===$v));}foreach(['province_id','city_id'] as $k)if($id=(int)$r->get_param($k))$data=array_values(array_filter($data,static fn($x)=>($x['location'][$k]??0)===$id));return Response::cache(Response::ok($data),'public, max-age=60, stale-while-revalidate=300');}
 public function get(WP_REST_Request $r){$id=(int)$r['id'];$d=Serializer::square($id,!$this->bool($r->get_param('defer_counts')));return $d&&get_post_status($id)==='publish'?Response::cache(Response::ok($this->enrich($d,$id)),'public, max-age=60, stale-while-revalidate=300'):Response::error('not_found','میدان پیدا نشد.',404);}
 public function narratives(WP_REST_Request $r){$sid=(int)$r['id'];if(!UserAccess::visibleSquare($sid))return Response::error('not_found','میدان پیدا نشد.',404);$ownerId=Actor::squareOwnerUserId($sid);return ProfileNarrativePage::listByAuthor($ownerId,$r,'square:'.$sid,true);}

 public function mediaReflectionCount(WP_REST_Request $r){$sid=(int)$r['id'];if(!UserAccess::visibleSquare($sid)||get_post_status($sid)!=='publish')return Response::error('not_found','میدان پیدا نشد.',404);$count=self::mediaReflectionTotal($sid,Actor::squareOwnerUserId($sid));return Response::cache(Response::ok(['square_id'=>$sid,'count'=>$count]),'public, max-age=60, stale-while-revalidate=300');}
 /** Reflections on a square's narratives; cached for a minute because the query joins postmeta twice. */
 public static function mediaReflectionTotal(int $sid,int $ownerId):int{$key='meydan_square_reflections_'.$sid;$count=get_transient($key);if($count!==false)return (int)$count;global $wpdb;$sql="SELECT COUNT(*) FROM {$wpdb->prefix}meydan_media_reflections mr INNER JOIN {$wpdb->posts} p ON p.ID=mr.narrative_id WHERE p.post_type='meydan_narrative' AND p.post_status='publish' AND p.post_author=%d AND mr.status='published'";$count=(int)$wpdb->get_var($wpdb->prepare($sql,$ownerId));set_transient($key,$count,MINUTE_IN_SECONDS);return $count;}
 public function schedule(WP_REST_Request $r){$sid=(int)$r['id'];if(!UserAccess::visibleSquare($sid))return Response::error('not_found','میدان پیدا نشد.',404);return Response::ok(Serializer::squareSchedule($sid));}
 public function map(WP_REST_Request $r){global $wpdb;$where=['p.post_type=\'meydan_square\'','p.post_status=\'publish\''];$args=[];foreach(['province_id','city_id'] as $k)if($r->get_param($k)!==null){$where[]='g.'.$k.'=%d';$args[]=(int)$r->get_param($k);}if($r->get_param('west')!==null){$where[]='g.longitude >= %f';$args[]=(float)$r->get_param('west');}if($r->get_param('east')!==null){$where[]='g.longitude <= %f';$args[]=(float)$r->get_param('east');}if($r->get_param('south')!==null){$where[]='g.latitude >= %f';$args[]=(float)$r->get_param('south');}if($r->get_param('north')!==null){$where[]='g.latitude <= %f';$args[]=(float)$r->get_param('north');}$sql="SELECT g.*,p.post_title,pr.name AS province_name,c.name AS city_name FROM {$wpdb->prefix}meydan_square_geo g JOIN {$wpdb->posts} p ON p.ID=g.square_id LEFT JOIN {$wpdb->prefix}meydan_provinces pr ON pr.id=g.province_id LEFT JOIN {$wpdb->prefix}meydan_cities c ON c.id=g.city_id WHERE ".implode(' AND ',$where)." LIMIT 1000";if($args)$sql=$wpdb->prepare($sql,...$args);$rows=$wpdb->get_results($sql,ARRAY_A);$features=[];foreach($rows?:[] as $row){$id=(int)$row['square_id'];if(!UserAccess::visibleSquare($id))continue;$features[]=['type'=>'Feature','geometry'=>['type'=>'Point','coordinates'=>[(float)$row['longitude'],(float)$row['latitude']]],'properties'=>['id'=>$id,'name'=>Actor::squareDisplayName($id),'verified'=>(bool)get_post_meta($id,'meydan_verified',true),'province_id'=>(int)$row['province_id'],'province_name'=>(string)$row['province_name'],'city_id'=>(int)$row['city_id'],'city_name'=>(string)$row['city_name'],'avatar_url'=>Actor::squareAvatarUrl($id)]];}return Response::cache(Response::ok(['type'=>'FeatureCollection','features'=>$features]),'public, max-age=60, stale-while-revalidate=300');}
 private function enrich(?array $data,int $id):?array{if(!$data)return null;$p=get_post($id);$ownerId=Actor::squareOwnerUserId($id);$data['slug']=$p?$p->post_name:(string)$id;$data['chat_user_id']=$ownerId?:null;$data['handle']=$ownerId?Handles::ofUser($ownerId):(string)get_post_meta($id,'meydan_handle',true);$data['subtitle']=(string)get_user_meta($ownerId,'meydan_headline',true)?: (string)get_post_meta($id,'meydan_subtitle',true);$data['profile_about']=(string)get_user_meta($ownerId,'meydan_about',true)?: (string)get_post_meta($id,'meydan_profile_about',true);$data['profile_skills']=array_values((array)get_user_meta($ownerId,'meydan_skills',true)?: (array)get_post_meta($id,'meydan_profile_skills',true));$data['square_stats']=array_values((array)get_post_meta($id,'meydan_square_stats',true));$data['resume_stats']=array_values((array)get_post_meta($id,'meydan_resume_stats',true));$data['start_date']=SquareActivity::startDate($id);$data['verified']=(bool)get_post_meta($id,'meydan_verified',true);$data['stats']=is_array($data['stats']??null)?$data['stats']:[];global $wpdb;$data['stats']['followers']=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}meydan_interactions WHERE object_type='square' AND object_id=%d AND action='follow'",$id));$data['stats']['active_nights']=SquareActivity::activeNights($id);return $data;}
}
