<?php
declare(strict_types=1);namespace Meydan\Core\Rest;
use Meydan\Core\Support\Response;use Meydan\Core\Support\Serializer;use Meydan\Core\Support\Stats;use Meydan\Core\Timeline\CandidateGenerator;use Meydan\Core\Timeline\FeatureHydrator;use Meydan\Core\Timeline\Mixer;use Meydan\Core\Timeline\Ranker;use WP_REST_Request;
final class TimelineController extends BaseController
{
 public function timeline(WP_REST_Request $r){$viewer=$this->viewer();$mode=sanitize_key((string)($r->get_param('mode')?:'for_you'));$filter=sanitize_key((string)($r->get_param('filter')?:'all'));$gen=new CandidateGenerator();if($mode==='following'){if(!$viewer->isAuthenticated())return Response::error('unauthenticated','Timeline دنبال‌شوندگان نیاز به ورود دارد.',401);$items=$gen->followingChronological($viewer->userId,100);}else{$features=(new FeatureHydrator())->hydrate($viewer,$gen->generate($viewer));$items=(new Mixer())->mixAndDiversify((new Ranker())->rank($features),100);}if($filter!=='all')$items=array_values(array_filter($items,fn($x)=>$this->matches($x['id'],$filter)));$items=array_slice($items,0,100);$ids=array_column($items,'id');Stats::incrementViewsBulk($ids);$this->record($viewer,$ids,$mode);$data=array_values(array_filter(array_map([Serializer::class,'narrative'],$ids)));return Response::cache(Response::ok($data,['next_cursor'=>null,'count'=>count($data)]),'private, no-store');}
 private function matches(int $id,string $f):bool{$a=(array)get_post_meta($id,'meydan_attachments',true);return match($f){'echo'=>(bool)get_post_meta($id,'meydan_is_echo',true),'reflected'=>Serializer::mediaReflections($id)!==[],'initiatives'=>(int)get_post_meta($id,'meydan_initiative_id',true)>0,'visual'=>(bool)array_filter($a,static fn($x)=>str_starts_with((string)get_post_mime_type((int)($x['media_id']??0)),'image/')||str_starts_with((string)get_post_mime_type((int)($x['media_id']??0)),'video/')),'audio'=>(bool)array_filter($a,static fn($x)=>str_starts_with((string)get_post_mime_type((int)($x['media_id']??0)),'audio/')),default=>true};}
 private function record($v,array $ids,string $source):void{if(!$ids)return;global $wpdb;$table=$wpdb->prefix.'meydan_served_history';$vid=$v->isAuthenticated()?(string)$v->userId:$v->guestId;foreach($ids as $id)$wpdb->insert($table,['viewer_type'=>$v->type,'viewer_id'=>$vid,'narrative_id'=>(int)$id,'served_at'=>current_time('mysql',true),'source'=>$source]);}
}
