<?php
declare(strict_types=1);namespace Meydan\Core\Rest;
use Meydan\Core\Support\Cursor;use Meydan\Core\Support\Response;use Meydan\Core\Support\Serializer;use Meydan\Core\Support\Stats;use Meydan\Core\Timeline\CandidateGenerator;use Meydan\Core\Timeline\FeatureHydrator;use Meydan\Core\Timeline\Mixer;use Meydan\Core\Timeline\Ranker;use WP_REST_Request;
final class TimelineController extends BaseController
{
 public function timeline(WP_REST_Request $r){$viewer=$this->viewer();$mode=sanitize_key((string)($r->get_param('mode')?:'for_you'));$filter=sanitize_key((string)($r->get_param('filter')?:'all'));$limit=min(50,max(1,(int)($r->get_param('limit')?:20)));$offset=max(0,(int)(Cursor::decode((string)$r->get_param('cursor'))['o']??0));if($mode==='for_you'&&in_array($filter,['initiatives','reflected'],true))return $this->filteredTimeline($viewer,$filter,$limit,$offset);$gen=new CandidateGenerator();if($mode==='following'){if(!$viewer->isAuthenticated())return Response::error('unauthenticated','Timeline دنبال‌شوندگان نیاز به ورود دارد.',401);$items=$gen->followingChronological($viewer->userId,100);}else{$features=(new FeatureHydrator())->hydrate($viewer,$gen->generate($viewer));$items=(new Mixer())->mixAndDiversify((new Ranker())->rank($features),100);}if($filter!=='all')$items=array_values(array_filter($items,fn($x)=>$this->matches($x['id'],$filter)));$total=count($items);$items=array_slice($items,$offset,$limit);$ids=array_column($items,'id');Stats::incrementViewsBulk($ids);$this->record($viewer,$ids,$mode);$data=array_values(array_filter(array_map([Serializer::class,'narrative'],$ids)));$next=$offset+$limit<$total?Cursor::encode(['o'=>$offset+$limit]):null;return Response::cache(Response::ok($data,['next_cursor'=>$next,'count'=>count($data)]),'private, no-store');}
 private function filteredTimeline($viewer,string $filter,int $limit,int $offset){$take=$limit+1;if($filter==='initiatives'){$q=new \WP_Query(['post_type'=>'meydan_narrative','post_status'=>'publish','posts_per_page'=>$take,'offset'=>$offset,'fields'=>'ids','orderby'=>'date','order'=>'DESC','no_found_rows'=>true,'meta_query'=>[['key'=>'meydan_initiative_id','value'=>0,'compare'=>'>','type'=>'NUMERIC']]]);$ids=array_map('intval',$q->posts);}else{global $wpdb;$ids=array_map('intval',$wpdb->get_col($wpdb->prepare("SELECT DISTINCT p.ID FROM {$wpdb->posts} p INNER JOIN {$wpdb->prefix}meydan_media_reflections mr ON mr.narrative_id=p.ID AND mr.status='published' WHERE p.post_type='meydan_narrative' AND p.post_status='publish' ORDER BY p.post_date_gmt DESC,p.ID DESC LIMIT %d OFFSET %d",$take,$offset))?:[]);} $hasMore=count($ids)>$limit;if($hasMore)$ids=array_slice($ids,0,$limit);Stats::incrementViewsBulk($ids);$this->record($viewer,$ids,'filter_'.$filter);$data=array_values(array_filter(array_map([Serializer::class,'narrative'],$ids)));$next=$hasMore?Cursor::encode(['o'=>$offset+$limit]):null;return Response::cache(Response::ok($data,['next_cursor'=>$next,'count'=>count($data)]),'private, no-store');}
 private function matches(int $id,string $f):bool{$a=(array)get_post_meta($id,'meydan_attachments',true);$hasVisual=(bool)array_filter($a,static fn($x)=>str_starts_with((string)get_post_mime_type((int)($x['media_id']??0)),'image/')||str_starts_with((string)get_post_mime_type((int)($x['media_id']??0)),'video/'));$hasAudio=(bool)array_filter($a,static fn($x)=>str_starts_with((string)get_post_mime_type((int)($x['media_id']??0)),'audio/'));return match($f){'echo'=>(bool)get_post_meta($id,'meydan_is_echo',true),'reflected'=>Serializer::mediaReflections($id)!==[],'initiatives'=>(int)get_post_meta($id,'meydan_initiative_id',true),'visual'=>$hasVisual,'audio'=>$hasAudio,'media'=>$hasVisual||$hasAudio,'ideas'=>!$hasVisual&&!$hasAudio&&!((bool)get_post_meta($id,'meydan_is_echo',true)),default=>true};}
 private function record($v,array $ids,string $source):void{if(!$ids)return;global $wpdb;$table=$wpdb->prefix.'meydan_served_history';$vid=$v->id;foreach($ids as $id)$wpdb->insert($table,['viewer_type'=>$v->type,'viewer_id'=>$vid,'narrative_id'=>(int)$id,'served_at'=>current_time('mysql',true),'source'=>$source]);}
}
